environments:
     - name: PROD
       configs:
          endpoints:
              production:
                  url: 'https://localhost:9463/am/sample/pizzashack/v1/api/'
              sandbox:
                  url: 'http://www.dneonline.com/calculator.asmx'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Gold 
     - name: DEV
       configs:
          endpoints:
              production:
                  url: 'https://localhost:9453/am/sample/pizzashack/v1/api/'
              sandbox:
                  url: 'https://localhost:9453/am/sample/pizzashack/v1/api/'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Bronze 
