environments:
    - name: PROD
      configs:
          endpoints:
              production:
                  url: 'http://www.dneonline.com/calculator.asmx'
              sandbox:
                  url: 'http://www.dneonline.com/calculator.asmx'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Gold 
    - name: DEV 
      configs:
          endpoints:
              production:
                  url: 'http://www.dneonline.com/calculator.asmx'
              sandbox:
                  url: 'http://www.dneonline.com/calculator.asmx'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Silver 
              
