environments:
    - name: PROD
      configs:
          endpoints:
              production:
                  url: 'http://production.com/calculator.asmx'
              sandbox:
                  url: 'http://www.production.sand.com/calculator.asmx'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
          policies:
              - Gold 
              - Silver
